### PR TITLE
Feature/issue 181/add dietary restrictions to donor orders page

### PR DESCRIPTION
**Pull request by maxgrove42**
# #181

## Description

- Restyles the Donor Dashboard - Orders tab to fit everything in and support mobile view
  - Pull pickup date into the dropdown title since pickup date is by food item
  - Remove address since we are in the donor dashboard and the address will be the same for every order
- Groups orders by food item
- Uses cards to display the orders by recipient
- Displays Dietary Restrictions on card 

Screenshot 2024-11-01 at 10 31 57 AM
Screenshot 2024-11-01 at 10 34 18 AM
Screenshot 2024-11-01 at 10 34 23 AM

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by QahtanAlJammali — APPROVED** [review]
Looking sleek! wow love it!

**Comment by maxgrove42** [comment]
Converted to DRAFT while "Mark as _______ " is changed to a dropdown menu for complete or pending.

**Comment by maxgrove42** [comment]
Added in a current status and use the mark as pending or complete as blue instead of red/green. Dropdown will be a pretty big lift and require AJAX, so keeping to a button. 

Screenshot 2024-11-04 at 6 34 32 PM

**Review by QahtanAlJammali — APPROVED** [review]
LGTM! can't wait to see in prod

**Pull request merged**
