### PR TITLE
Feature/issue 46/view manage organization page

### PR DESCRIPTION
**Pull request by TekuriSaiAkhil**
# [Issue 46](https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/46)

## Description

Made changes required to fit into the new database models
Created HTML page and required routing for Managing organizations.

## Change Type (delete non-relevant options)

- 🪲 Bug fix (non-breaking change which fixes an issue)
- 💡 New feature (non-breaking change which adds functionality)

## Dependencies

- Qahtan's PR on Database

### CODE REVIEW

**Review by maxgrove42 — COMMENTED** [review]
Nice !

**Review by maxgrove42 — APPROVED** [review]
nice !

**Review by QahtanAlJammali — APPROVED** [review]
Amazing Thank you very much!

**Comment by QahtanAlJammali** [comment]
Great, thank you for catching the issue with organization_name.
for conflict resolution:
admin_id in organizationadmin
review_id in userreviews
message_id in message
order_id in order
and organization_name fixes the two typos. 

Awesome awesome work!

**Pull request merged**
