### PR TITLE
Feature/issue 47/initial setup

### PR DESCRIPTION
**Pull request by maxgrove42**
# [Issue 47](https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/47)

## Description

- Initial setup of repository for Django
- Adds linting capabilities to ensure code styling compatibility

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

## Dependencies

- This branch contains a breaking change ⚠️
  -  Requires developers to follow development setup instructions in `README`

### CODE REVIEW

**Review by TekuriSaiAkhil — APPROVED** [review]
Looks great to me!!

**Comment by estchang** [comment]
Thanks Max! Setup works great for me!

**Review by QahtanAlJammali — APPROVED** [review]
Looks great! Thank you Max.

**Review by arsalananwar11 — APPROVED** [review]
LGTM, Thanks Max!

**Pull request merged**
