### PR TITLE
Delete Community Drive Functionality

### PR DESCRIPTION
**Pull request by maxgrove42**
# #382

## Description

- Implements functionality to delete (aka inactivate) a community drive
- Sets all pledges to 0
- Sets drive to inactive

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by QahtanAlJammali — APPROVED** [review]
Ah, darn Black requires to reformat one file, but otherwise looking great! Thanks Max!

**Comment by QahtanAlJammali** [comment]
seems to be failing one of the tests written for it

**Comment by maxgrove42** [comment]
@QahtanAlJammali  ah yes. one of the linting requirements was no blank EXCEPTs and i updated one of the error messages. Quick and easy fix.

**Comment by maxgrove42** [comment]
@QahtanAlJammali  updated test!

**Comment by QahtanAlJammali** [comment]
Sweet! time to squash and merge! 🙌

**Pull request merged**
