### PR TITLE
Feature/issue 49/initial accounts setup

### PR DESCRIPTION
**Pull request by maxgrove42**
# [Issue 49](https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/49)

## Description

- Create the accounts app
- Define URL patterns for the accounts app
- Add routes for login, registration, logout, and profile management in accounts/urls.py.
- Include the accounts URL patterns in the main urls.py file.
- Set up templates:
  - Create templates for login (login.html), registration (register.html), and profile management (profile.html) in accounts/templates/accounts/.
  - Ensure the templates inherit from the base template (base.html)
- Ensure root URL redirects to the login page:
  - Update the main urls.py to redirect the root URL (/) to the login page.
- Test the accounts app:
  - Verify that login, registration, and logout functionality works as expected.

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

## Dependencies

- No dependencies

### CODE REVIEW

**Review by TekuriSaiAkhil — APPROVED** [review]
Looks good to me

**Review by estchang — APPROVED** [review]
Looks great!!

**Review by QahtanAlJammali — APPROVED** [review]
Looks awesome thank you!

**Review by arsalananwar11 — APPROVED** [review]
Looks good!

**Pull request merged**
