### PR TITLE
Manage Org Bug Fix for Cancelled orders

### PR DESCRIPTION
**Pull request by maxgrove42**
# #319: [BUG] - Organization can change a canceled order into pending/complete

## Description

- Adjusted if-else logic on front-end in `manage-organization` to account for the `cancelled` status. 
- Added in improved sorting on back-end to sort by order status after sorting by donation_id and pickup_date
- New UI
  - Screenshot 2024-11-23 at 11 44 53 AM

## Change Type (delete non-relevant options)

- 🪲 Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by arsalananwar11** [comment]
Just a thought- should we just show the pending orders under the dropdown and show all orders (pending, completed and cancelled) when the users download CSV. 

This I feel will be much cleaner for the donors to focus on orders which are pending.

**Comment by maxgrove42** [comment]
Sure! Will revert on thisSent from my iPhoneOn Nov 23, 2024, at 2:03 PM, Arsalan Anwar ***@***.***> wrote:﻿
@maxgrove42  Just a thought- should we just show the pending orders under the dropdown and show all orders (pending, completed and cancelled) when the users download CSV.
This I feel will be much cleaner for the donors to focus on orders which are pending.

**Comment by maxgrove42** [comment]
@arsalananwar11 this is updated !

**Review by QahtanAlJammali — APPROVED** [review]
Awesome work, thank you Max!

**Pull request merged**
