### PR TITLE
bugfix/issue 293/frontend pickup date fix

### PR DESCRIPTION
**Pull request by estchang**
# Issue #293 

## Description

Fixes bug where the date warning was appearing when the pickup date for a new donation was set to today

## Change Type (delete non-relevant options)

- 🪲 Bug fix (non-breaking change which fixes an issue)

## Dependencies

- No dependencies

### CODE REVIEW

**Comment by maxgrove42** [comment]
oh noooo i might have already solved this. looks like we have double PRs for this issue

My PR: https://github.com/gcivil-nyu-org/wed-fall24-team5/pull/339

Issue describing same bug: https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/300

**Comment by estchang** [comment]
> oh noooo i might have already solved this. looks like we have duplicated issues for this bug
> 
> My PR: #339
> 
> Issue describing same bug: #300

oh no!! totally did not catch that lol, I'll go ahead and close this PR and issue then

**Comment by maxgrove42** [comment]
oh wait @estchang

**Comment by estchang** [comment]
> oh wait @estchang

yeah I just realized!! LOL will reopen

**Comment by maxgrove42** [comment]
vs mine was to get the logic working where sometimes the tomorrow pickup date didn't work depending on the hour.

**Review by maxgrove42 — APPROVED** [review]
approved. SORRY LOL

**Review by arsalananwar11 — APPROVED** [review]
Neat! Thanks @estchang

**Pull request merged**
