### PR TITLE
Feature/issue 59/prepare aws deployment

### PR DESCRIPTION
**Pull request by maxgrove42**
# [Issue 59](https://github.com/gcivil-nyu-org/wed-fall24-team5/issues)

## Description

- Adds code to deploy to Elastic Beanstalk
- Serves the `static` files to ensure CSS
- It's tied to my AWS Account now, but I'll look into how we can setup getting everyone's accounts access to the environment.
- Deployed to: http://food-donation-swe-dev.us-east-1.elasticbeanstalk.com/

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

## Dependencies

- I will explain the deploy process this week. Right now, it is manual, but Anthony said we'll be setting up CI/CD pipelines in class this week.

### CODE REVIEW

**Review by QahtanAlJammali — APPROVED** [review]
Looks great thanks Max!

**Review by TekuriSaiAkhil — APPROVED** [review]
looks good

**Review by arsalananwar11 — APPROVED** [review]
Good Job, Thanks Max!

**Review by estchang — APPROVED** [review]
Thanks so much!

**Pull request merged**
