### PR TITLE
Add in stars to recipient dashboard

### PR DESCRIPTION
**Pull request by maxgrove42**
# #19 - Task 2

## Description

- Add in an organization's average stars to the recipient dashboard.

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by estchang — COMMENTED** [review]
Looks good!! However I'm now having some trouble getting the stars to show up on the review modal itself - i think they appear for some orders but for others i'm just seeing the comment box

**Comment by maxgrove42** [comment]
> Looks good!! However I'm now having some trouble getting the stars to show up on the review modal itself - i think they appear for some orders but for others i'm just seeing the comment box

Interesting. Since we've already merged this, could you open a Bug Issue and we can address it next sprint? Steps to reproduce and screenshots would be great! @estchang Thanks for flagging and finding!

**Comment by estchang** [comment]
> > Looks good!! However I'm now having some trouble getting the stars to show up on the review modal itself - i think they appear for some orders but for others i'm just seeing the comment box
> 
> Interesting. Since we've already merged the review modal and this PR is to just display stars on the recipient dashboard, could you open a Bug Issue and we can address it next sprint? Steps to reproduce and screenshots would be great! @estchang Thanks for flagging and finding!

Got it, will do that! The bug's not appearing for me on the develop branch so I wondered if it might be due to the changes in this PR, but I'll hold off until someone else can double check - maybe it's just a display issue on my end.

**Comment by maxgrove42** [comment]
@estchang I see it now on develop site when I click back and forth on reviews a few times. it seems like it just isn't displaying the top half of the modal... argh !!! great find! :)

**Comment by arsalananwar11** [comment]
> @estchang I see it now on develop site when I click back and forth on reviews a few times. it seems like it just isn't displaying the top half of the modal... argh !!! great find! :)

Hey @maxgrove42, is this something you have fixed or are planning to fix? Should I wait to review the PR until this is resolved?

**Review by arsalananwar11 — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
