### PR TITLE
Bugfix/issue 234/delete buttons not working in org page

### PR DESCRIPTION
**Pull request by TekuriSaiAkhil**
# [Issue 234](https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/234)

## Description

Fix to "Delete buttons not working in organization page"

## Change Type (delete non-relevant options)

- 🪲 Bug fix (non-breaking change which fixes an issue)

## Dependencies

- None

### CODE REVIEW

**Review by maxgrove42 — CHANGES_REQUESTED** [review]
Since technically we aren't "deleting" the organization, just making it inactive, could we call the delete button "Set as Inactive" ?

Screenshot 2024-11-11 at 7 19 06 AM

**Review by QahtanAlJammali — APPROVED** [review]
LGTM. thank you

**Comment by TekuriSaiAkhil** [comment]
> Since technically we aren't "deleting" the organization, just making it inactive, could we call the delete button "Set as Inactive" ?
> 
> Screenshot 2024-11-11 at 7 19 06 AM

This makes sense, I'll update it.

**Comment by TekuriSaiAkhil** [comment]
Update to `Make Organization Inactive` and updated the prompt text to `Are you sure you want to make this organization inactive? All the donations and orders under this organization will also be inactive!!`

**Review by maxgrove42 — APPROVED** [review]
im all good here! Thanks!

**Pull request merged**
